services:
  api:
    build: ./api
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=roman_coins
    ports:
      - 8010:80
    depends_on:
      db:
        condition: service_healthy
  web_scraper:
    build: ./web_scraping
    volumes:
      - flag:/app/data
    depends_on:
      db:
        condition: service_healthy
#    command: tail -f /dev/null # Uncomment to keep web_scraper running manually
  db:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=roman_coins
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test_db:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_database
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  flag:
