version: 2

sources:
  - name: main
    database: data
    tables:
      - name: raw_roman_coins
        meta:
          dagster:
            asset_key: ["raw_roman_coins"] # This metadata specifies the corresponding Dagster asset for this dbt source.
