name: Deploy Custom Airbyte Connector

on:
  push:
    branches: [ master ]
    paths:
      - 'custom-airbyte-connector/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Custom Airbyte Connector Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/roman-coins-data-pipeline:custom-airbyte-connector-${{ github.sha }} ./custom-airbyte-connector
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/roman-coins-data-pipeline:custom-airbyte-connector-latest ./custom-airbyte-connector
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/roman-coins-data-pipeline:custom-airbyte-connector-${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/roman-coins-data-pipeline:custom-airbyte-connector-latest